config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index', as: 'tasks_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  patch '/done/:id', to: 'tasks#done', as: :done_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def edit
    @task =Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task
    else
      render action: 'edit'
    end
  end

  def show
    @task =Task.find(params[:id])
  end

  def index
    @tasks = Task.all
  end
  def new

  end

  def create
    @task = Task.new(task_params)
    if @task.valid?
      @task.save
      redirect_to @task
    else
      render action: 'new'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy


  end



  private
  def task_params
    params.require(:task).permit(:title, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>ok</h1>


<p></p>

app/views/tasks/create.html.erb
<h1> Task created </h1>

<%= link_to 'Show all task', tasks_path %>

app/views/tasks/destroy.html.erb
<h1> Destroy </h1>

app/views/tasks/edit.html.erb
<h1> Edit task </h1>
<%= form_for :task, url: task_path(@task), method: :put  do |f| %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %>
    <%=f.text_area :text %>
  </p>
  <p>
    <%= f.submit %> <br/>
  </p>

<% end %>

app/views/tasks/index.html.erb
<h1> All tasks </h1>

<% @tasks.each do |task| %>
  <h2>
    <%= task.title %>
  </h2>
  <p>
    <%= task.text %>
  </p>

  <p>
    <%= link_to 'Show', task_path(task) %>
    <%= link_to 'Edit', edit_task_path(task) %>
    <%= link_to 'Destroy', task_path(task), method: :delete %>
  </p>
  <hr/>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for :task, url: '/tasks'  do |f| %>
  <% if @task && @task.errors.any? %>
  <p>
      <ul>
      <%@task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
          <% end %>
      </ul>
  </p>
    <%end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :text %>
  <%=f.text_area :text %>
  </p>


  <p>
    <%= f.submit %> <br/>
  </p>


<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p> <%= @task.text  %></p>